name: 'Init Tools'
description: ''
inputs: {}
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        /usr/bin/env bash
        test -f /usr/local/bin/yq        || ( sudo curl -vL https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64 -o /usr/local/bin/yq      && sudo chmod +x /usr/local/bin/yq )
        test -f /usr/local/bin/ossutil   || ( sudo curl -vL https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64                   -o /usr/local/bin/ossutil && sudo chmod +x /usr/local/bin/ossutil )
        test -f /usr/local/bin/kubectl   || ( sudo curl -vL https://dl.k8s.io/release/v1.24.2/bin/linux/amd64/kubectl                -o /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl )
        test -f /usr/local/bin/kustomize || ( curl -vL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz | sudo tar -zxf - -C /usr/local/bin/; sudo chmod +x /usr/local/bin/kustomize )
