name: 'Init Tools'
description: ''
inputs:
  kubeconfig:
    description: 'Kube Config Base64'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: framely/actions-composite-expand@main
      with:
        main: |-
          /usr/bin/env bash
          echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          (docker context ls | grep builders) || docker context create builders

          git config --global user.name  github-actions
          git config --global user.email github-actions@github.com

          test -f /usr/local/bin/yq        || ( sudo curl -vL https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64 -o /usr/local/bin/yq      && sudo chmod +x /usr/local/bin/yq )
          test -f /usr/local/bin/ossutil   || ( sudo curl -vL https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64                   -o /usr/local/bin/ossutil && sudo chmod +x /usr/local/bin/ossutil )
          test -f /usr/local/bin/kubectl   || ( sudo curl -vL https://dl.k8s.io/release/v1.24.2/bin/linux/amd64/kubectl                -o /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl )
          test -f /usr/local/bin/kustomize || ( curl -vL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz | sudo tar -zxf - -C /usr/local/bin/; sudo chmod +x /usr/local/bin/kustomize )

          if [ ! '${{ inputs.kubeconfig }}' == '' ]; then
              mkdir -p ~/.kube/
              echo -n ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config
          fi
        post: |-
          rm -rf ~/.kube/
